import os
from dotenv import load_dotenv
import streamlit as st  
from helper_functions.utility import check_password  
from helper_functions import llm
import pandas as pd
import numpy as np
import json
import plotly.graph_objects as go

load_dotenv('.env')

# Check if the password is correct.  
if not check_password():  
    st.stop()

#Intro

st.set_page_config(
    layout="centered",
    page_title="Main"
)

#Defining Functions

#Download button (Converting df)
@st.cache_data
def convert_df(df):
    # IMPORTANT: Cache the conversion to prevent computation on every rerun
    return df.to_csv().encode("utf-8-sig")

#Main portion

st.title("Identifying Digital Manipulation")

# form = st.form(key="form")
# form.subheader("Prompt")

# user_prompt = form.text_area("Enter your prompt here", height=200)

# if form.form_submit_button("Submit"):
#     st.toast(f"User Input Submitted - {user_prompt}")
#     response = llm.get_completion(user_prompt) # <--- This calls the helper function that we have created 🆕
#     st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
#     print(f"User Input is {user_prompt}")

#Preparation for Running of File
column_names = {
    'Step 1': 'AI_ML_Presence',
    'Step 2': 'DM_Victim',
    'Step 3': 'DM_Celebrity',
    'Step 4': 'DM_Victim_Related',
    'Final Answer': 'Presence_of_DM'
}


#Upload file button
uploaded_file = st.file_uploader(label="Upload .csv document containing facts of case below.",
                 type=['csv'])

#Click button
if 'clicked' not in st.session_state:
    st.session_state.clicked = False
def click_button():
    st.session_state.clicked = True

#Uploading files
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file, index_col=False)
    st.write(df)
    st.write("Is the file above correct? Do ensure that the facts of case column is labelled 'FACTS'")
    st.button('Run LLM!', on_click=click_button)

if st.session_state.clicked:
    st.toast(f"Checking for presence of digital manipulation in your file...")

    #Create empty df
    df_responses = pd.DataFrame()

    #For each facts in the df['FACTS']...take the facts and put in prompt and send to LLM
    for facts in df['FACTS']:
        prompt = f"""
You are a police officer investigating cases of “Digital Manipulation”.

“Digital manipulation” reports: Refers to cases where there are alteration/enhancement/modifications from simple digital editing to the use of AI/ML technologies used on photos, videos, and audio. Use of Deepfake or any other AI/ML technologies is also considered digital manipulation. 
Only consider the cases as digital manipulation if there are editing used on photos/videos/audio or when Artificial Intelligence or Machine Learning technologies are used. 
<Facts> will be given in the next paragraph for you to determine whether they are digital manipulation cases.
I want you to explain whether there is proof of digital manipulation and think about it step by step. 
Only say yes when there is sufficient proof of digital manipulation. If it is a potential fraudulent transaction or exchange, and no evidence of digital manipulation, it is NOT a case of digital manipulation.

<Facts>
{facts}
<Facts>

<Steps>
Step 1: Evaluate whether there is use of Artificial Intelligence or Machine Learning in the case?
Step 2: Evaluate whether there is digital manipulation of the victim? (i.e, victim's own photo/audio/video was altered or superimposed?)
Step 3: Evaluate whether there is digital manipulation of famous celebrities or well known person involved?
Step 4: Evaluate whether there is digital manipulation of someone related to the victim? This can be a call or whatsapp video mimicking someone. This can be the victim’s family member such as mother or father, or friends.
</Steps>

If the answer is yes to any of the steps, then the report is considered a case of digital manipulation.
Double check and go through step 1 to 4 before giving me your final answer.

Your entire response/output is going to consist of a single JSON object with only "Yes/No" answers, and you will NOT wrap it within JSON md markers\
Provide them in JSON format only with the following keys below.:
Step 1, Step 2, Step 3, Step 4, Final Answer.

"""
        response = llm.get_completion(prompt)
        response_dict = json.loads(response)
        current_response_df = pd.DataFrame(response_dict, index = [0])
        df_responses = pd.concat([df_responses,current_response_df], ignore_index=True)
    df_combined = pd.concat([df,df_responses],axis = 1)
    df_combined.rename(columns=column_names, inplace = True)
    st.write(df_combined)

    #Convert df to csv file to prep for download
    csv = convert_df(df_combined)

    #Download button
    st.download_button(
        label="Download data as CSV",
        data=csv,
        file_name="results.csv",
        mime="text/csv",
    )
    
    #Plotly Pie Chart

    # Count occurrences of each value in the "Presence_of_DM" column
    count_dm = df_combined['Presence_of_DM'].value_counts()

    # Define colors for "Yes" and "No"
    colors = ['#1f77b4', '#ff7f0e']  # Blue for "Yes", Orange for "No"

    # Create a Pie chart with customized colors and sizes
    fig = go.Figure(data=[go.Pie(
    labels=count_dm.index,
    values=count_dm.values,
    textinfo='percent+label',  # Show percentage and label
    hole=.3,  # Optional: Use this for a donut chart; remove if you want a regular pie chart
    marker=dict(colors=colors),  # Set custom colors
    textfont=dict(size=20)  # Adjust font size
    )])
    # Add title
    fig.update_layout(title_text='Percentage of Reports with Presence of Digital Manipulation')

    # Display the chart in Streamlit
    st.plotly_chart(fig)

    #Inform summary
    st.toast("Creating summary report...")

    #Create a dataframe with only DM then convert to json
    df_combined_DM = df_combined.loc[df_combined['Presence_of_DM'] == "Yes",["FACTS","Presence_of_DM"]]
    
    df_combined_DM_json = df_combined_DM.to_json(orient="records")
    
    #Summarizing prompt
    summarize_prompt = f"""
You are an "digital manipulation" analyst for the Police Force. 
You are tasked with analyzing a series of police reports to create a detailed analytical report. 

“Digital manipulation” (DM) refers to cases where there are alteration/enhancement/modifications from simple digital editing to the use of AI/ML technologies used on photos, videos, and audio. 
Use of Deepfake or any other AI/ML technologies is also considered digital manipulation.

The report should summarize key findings and identify patterns. Focus on the following areas:

Incident Overview: Provide a summary of the cases in one paragraph, including the variant of digital manipulation (e.g., audio manipulation, video manipulation) if any. Highlight any significant incidents or outliers.

Patterns and Trends: Analyze the data to identify recurring themes or trends, such as consistent crime narratives, or even similar celebrity impersonated. Do give numbers to substantiate.

<Excel File>
{df_combined_DM_json}
</Excel File>
"""


    #Send json file in with prompt to create summarized finding
    response2 = llm.get_completion(summarize_prompt, temperature= 0.3, json_output=False)
    st.write(response2)

#Side bar

# pages = {
#     "Your account": [
#         st.Page("about.py", title="About Us"),
#         st.Page("methodology.py", title="Methodology"),
#     ],
#     # "Resources": [
#     #     st.Page("learn.py", title="Learn about us"),
#     #     st.Page("trial.py", title="Try it out"),
#     # ],
# }

# pg = st.navigation(pages,position = "hidden")
# pg.run()

#Disclaimer

st.expander("Disclaimer").write("""
IMPORTANT NOTICE: This web application is developed as a proof-of-concept prototype. The information provided here is NOT intended for actual usage and should not be relied upon for making any decisions, especially those related to financial, legal, or healthcare matters.
Furthermore, please be aware that the LLM may generate inaccurate or incorrect information. You assume full responsibility for how you use any generated output.
Always consult with qualified professionals for accurate and personalized advice.
         """)